# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jethrodaniel
description: >-
  A personal website
url: "jethrodaniel.com"
github_username:  jethrodaniel
linkedin_username: jethrodaniel
email: jethrodaniel@gmail.com
name: Mark Delk

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
