// Generated by CoffeeScript 2.5.1
/*
eslint-disable
*/
var e;

import React from 'react';

e = React.createElement;

import {
  Link
} from 'react-router-dom';

import {
  Col,
  Container,
  Row
} from 'reactstrap';

import './Terminal.css';

import Typing from 'react-typing-animation';

export var Terminal = () => {
  return e(Container, {}, e(Row, {
    className: 'justify-content-center'
  }, e(Col, {
    className: 'col-xs-12 col-sm-12 col-md-10 col-lg-8'
  }, e(Typing, {
    speed: 30
  }, e('p', {}, '$ cat > intro.txt'), e('p', {}, "I'm Mark Delk (aka Jethro)."), e('span', {}, 'See:'), e('p', {}, e('a', {
    href: 'https://github.com/jethrodaniel'
  }, 'Github')), e('p', {}, e('a', {
    href: 'http://basedeltazero.com'
  // e('p', {},
  //   e('a', {href: '/resume'}, 'Resume')
  // )
  }, 'My Band')), e('span', {}, '^D')))));
};

export default Terminal;
