// Generated by CoffeeScript 2.5.1
var HomePage, e;

import React from 'react';

e = React.createElement;

import {
  Col,
  Container,
  Navbar,
  Row
} from 'reactstrap';

import './home.css';

import {
  Terminal
} from '../../terminal.coffee';

export default HomePage = () => {
  return e('div', {
    id: "home-page"
  }, e(Navbar, {
    color: "dark",
    dark: true,
    expand: "md"
  }, e(Container, {
    fluid: true,
    className: "h-100"
  }, e(Row, {
    className: "w-100"
  }, e(Col, {
    md: "3",
    className: "d-none d-lg-block"
  }, null), e(Col, {
    id: "terminal"
  }, e(Terminal, {
    value: "Hello!"
  }, null)), e(Col, {
    md: "3",
    className: "d-none d-lg-block"
  }, null)))));
};
