// Generated by CoffeeScript 2.5.1
var App, NoMatch, e;

import React from 'react';

import ReactDOM from 'react-dom';

e = React.createElement;

import 'bootstrap/dist/css/bootstrap.min.css';

import './app.css';

import {
  BrowserRouter as Router,
  Route,
  Switch
} from 'react-router-dom';

import HomePage from './components/pages/home/home.coffee';

export default App = () => {
  return e(Router, {}, e('div', {}, e(Switch, {}, e(Route, {
    exact: true,
    path: "/",
    component: HomePage
  // e(Route, {exact: true, path: "/resume", component: Resume}, null)
  }, null), e(Route, {
    component: NoMatch
  }, null))));
};

NoMatch = ({location}) => {
  return e('div', {}, e('h3', {}, `No match for <code>${location.pathname}</code></h3>`));
};

ReactDOM.render(e(App, {}, null), document.getElementById('root'));
