// Generated by CoffeeScript 2.5.1
/*
eslint-disable
*/
var App, NoMatch, e;

import React from 'react';

e = React.createElement;

import {
  BrowserRouter as Router,
  Route,
  Switch
} from 'react-router-dom';

import HomePage from './components/pages/home/Home.js';

export default App = () => {
  return e(Router, {}, e('div', {}, e(Switch, {}, e(Route, {
    exact: true,
    path: "/",
    component: HomePage
  // e(Route, {exact: true, path: "/resume", component: Resume}, null)
  }, null), e(Route, {
    component: NoMatch
  }, null))));
};

NoMatch = ({location}) => {
  return e('div', {}, e('h3', {}, `No match for <code>${location.pathname}</code></h3>`));
};
