// Generated by CoffeeScript 2.5.1
import React from 'react';

import ReactDOM from 'react-dom';

import App from './app.coffee';

it('renders without crashing', () => {
  var div;
  div = document.createElement('div');
  ReactDOM.render(App, div);
  ReactDOM.unmountComponentAtNode(div); // nothing
});
