// Generated by CoffeeScript 2.5.1
/*
eslint-disable
*/
var e;

import React from 'react';

e = React.createElement;

import ReactDOM from 'react-dom';

import './index.css';

import 'bootstrap/dist/css/bootstrap.min.css';

import App from './App';

ReactDOM.render(e(App, {}, null), document.getElementById('root'));
